config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :news

  root to: "news#index"

  # authenticated :user do
  #   root to: "news#index"
  # end
  
  # unauthenticated :user do
  #   root to: "news#index"
  # end
  
  
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_news, only: %i[ show edit update destroy ]
  authorize_resource

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
    @edited_times = 5 - News.find(params[:id])[:edited_times]
  end

  # POST /news or /news.json
  def create
    @news = News.new(title: news_params[:title], content: news_params[:content], user_id: current_user.id)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "Новость успешно создана." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update

    

      edited_times = 1 + @news[:edited_times]

      if current_user.role == "reader"
        
        if edited_times <= 5
          respond_to do |format|
            if @news.update(title: news_params[:title], content: news_params[:content], edited_times: edited_times)
              format.html { redirect_to news_url(@news), notice: { text: "Новость успешно обновлена.", color: "green" } }
              format.json { render :show, status: :ok, location: @news }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @news.errors, status: :unprocessable_entity }
            end
          end
        else
        
          respond_to do |format|
            format.html { redirect_to @news, notice: { text: "Не осталось кол-ва редактирований !", color: "red" } }
            format.json { render json: @news.errors, status: :method_not_allowed }
          end
        
        end

      elsif current_user.role == "admin"
        respond_to do |format|
          if @news.update(title: news_params[:title], content: news_params[:content])
            format.html { redirect_to news_url(@news), notice: { text: "Новость успешно обновлена.", color: "green" } }
            format.json { render :show, status: :ok, location: @news }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @news.errors, status: :unprocessable_entity }
          end
        end
      end
    
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "Новость удалена." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :content)
    end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> запретил сохранение этой новости:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Заголовок", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, "Содержание", class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="">
    <p>Осталось редактирований: <%= @edited_times.to_s %></p>
  </div>
  
  <%= form.submit "Готово", class: "btn btn-primary" %>
<% end %>

app/views/news/_news.html.erb
<div class="col-12 col-sm-6 col-md-4" style="min-height: 260px" id="<%= dom_id news %>">
  <div class="card h-100" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= news.title %></h5>
      <p class="card-text"><%= truncate news.content, length: 100 %></p>
    </div>
    <div class="card-footer">
      <%= link_to "Посмотреть", news %>
    </div>
  </div>
</div>

app/views/news/_show.html.erb
<p>
    <%= news.content %>
</p>

app/views/news/edit.html.erb
<div class="container">
  <h1>Редактирование</h1>

  <%= render "form", news: @news %>
  
  <div>
    <%= link_to "Показать", @news %> |
    <%= link_to "Вернуться", news_index_path %>
  </div>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1 class="text-center mb-5">Новости</h1>
  <div id="news" class="row justify-content-center">
    <% @news.each do |news| %>
      <%= render news %>
    <% end %>
  </div>
</div>

app/views/news/new.html.erb
<div class="container">
  <h1>Создание</h1>

  <%= render "form", news: @news %>

  <br>

  <div>
    <%= link_to "Назад", news_index_path %>
  </div>
</div>

app/views/news/show.html.erb
<div class="container">
  <p style="color: <%= notice["color"] %>"><%= notice["text"] %></p>

  <h1 class="text-center mb-5"><%= @news.title %></h1>

  <%= render 'show', news: @news %>

  <% if can? :manage, @news %>
  <div>
    <%= link_to "Отредактировать", edit_news_path(@news) %> |
    <%= link_to "Вернуться", news_index_path %>

    <%= button_to "Удалить", @news, method: :delete, class: "btn btn-danger" %>
  </div>
  <% end %>
</div>