config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :news

  root to: "news#index"

  # authenticated :user do
  #   root to: "news#index"
  # end
  
  # unauthenticated :user do
  #   root to: "news#index"
  # end
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header >
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <%= link_to "TestSite", root_path, class: "navbar-brand" %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to "Главная", root_path, class: "nav-link", 'aria-current': 'home'%>
                </li>
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "Создать новость", new_news_path, class: 'nav-link' %>
                  </li>
                <% end %>
              </ul>
              <ul class="navbar-nav">
                <% if user_signed_in? %>
                  <li class="nav-item"><p class="navbar-text"><%= link_to current_user.email, edit_user_registration_path %></p></li>
                  <li class="nav-item"><%= button_to 'Выйти', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger ms-3" %></li>
                <% else %>
                    <li class="nav-item mx-2"><%= link_to 'Войти', new_user_session_path, class: 'btn btn-success' %></li>
                    <li class="nav-item"><%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-light' %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>

    <%= yield %>
  </body>
</html>